const projects = [
  {
    id: 'assemble',
    name: "Assemble",
    type: "Cross-platform Mobile App",
    timeline: "August 2020 - January 2021",
    descriptions: [
      "This is a local mobile app made for Singaporeans which allows them to form meaningful relationship. It features new daily matches, chat functionality, in-app notifications and functionality to report users for inappropriate behaviours.",
      "This project was built amidst Semester 2 of my final year in NUS as a pet project right after my internship at Webpuppies. This project was meant to be fun and also to reinforce the knowledge that I gained throughout my internship.",
      "This server to this project has been taken down since 28 May 2021.",
    ],
    devTools: [
      "NativeScript Vue",
      "Express",
      "Firebase services",
      "AWS services",
      "NginX",
    ],
    playstoreUrl:
      "https://play.google.com/store/apps/details?id=org.chalkboystudio.rootly",
    appstoreUrl:
      "https://apps.apple.com/us/app/assemble-local-dating-app/id1553270546",
    weburl: "",
    sourceCodeLink: "",
    images: [
      "/images/assemble/assemble_main.png",
      "/images/assemble/assemble_3.png",
      "/images/assemble/assemble_4.png",
      "/images/assemble/assemble_5.png",
      "/images/assemble/assemble_6.png",
      "/images/assemble/assemble_7.png",
      "/images/assemble/assemble_8.png",
      "/images/assemble/assemble_9.png",
      "/images/assemble/assemble_10.png",
      "/images/assemble/assemble_11.png",
    ],
  },
  {
    id: "emaily",
    name: "Emaily",
    type: "Web App",
    timeline: "Feb 2020",
    descriptions: [
      "A web app that allows user to mass send and track responses of survey emails. User logs in using Google OAuth, and pay via Stripe API.",
      "This project was built as part of a full stack web development course by Stephan Grider.",
    ],
    devTools: [
      "ReactJS",
      "Redux",
      "MongoDB",
      "Express",
      "OAuth",
      "Stripe",
      "Heroku",
    ],
    playstoreUrl: "",
    appstoreUrl: "",
    weburl: "https://murmuring-thicket-55187.herokuapp.com",
    sourceCodeLink: "https://github.com/francislow/emailyy",
    images: [
      "/images/emailyy/emailyy_main.png",
      "/images/emailyy/emailyy_2.png",
      "/images/emailyy/emailyy_3.png",
      "/images/emailyy/emailyy_4.png",
      "/images/emailyy/emailyy_5.png",
      "/images/emailyy/emailyy_6.png",
    ],
  },
  {
    id: "unmix",
    name: "Unmix",
    type: "Native Android App",
    timeline: "August 2019",
    descriptions: [
      "A native android application that allows user to store and manage pictures locally in a separate gallery.",
    ],
    devTools: ["Android", "Java", "SQLite", "Android SDK"],
    playstoreUrl:
      "https://play.google.com/store/apps/details?id=com.chalkboystudios.franc.unmix",
    appstoreUrl: "",
    weburl: "",
    sourceCodeLink: "https://github.com/francislow/unmix-photo-gallery",
    images: [
      "/images/unmix/unmix_main.png",
      "/images/unmix/unmix_2.png",
      "/images/unmix/unmix_3.png",
      "/images/unmix/unmix_4.png",
      "/images/unmix/unmix_5.png",
      "/images/unmix/unmix_6.png",
    ],
  },
  {
    id: "poofers",
    name: "Poofers",
    type: "Native Android App",
    timeline: "March 2017",
    descriptions: [
      "A native android 2D arcade game application developed using libGDX, a Java game development framework.",
      "Fun fact: This is my first ever mobile application that I have created.",
    ],
    devTools: ["Android", "Java", "libGDX", "InkScape", "Android SDK"],
    playstoreUrl:
      "https://play.google.com/store/apps/details?id=com.chalkboyygames",
    appstoreUrl: "",
    weburl: "",
    sourceCodeLink: "https://github.com/francislow/poofers",
    images: [
      '/images/poofers/poofers_main.png',
      '/images/poofers/poofers_2.png',
      '/images/poofers/poofers_3.png',
      '/images/poofers/poofers_4.png',
      '/images/poofers/poofers_5.png',
      '/images/poofers/poofers_6.png',
      '/images/poofers/poofers_7.png',
    ],
  },
];

export default projects;
